/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTransfersRouteImport } from './routes/app.transfers'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppProfilesRouteImport } from './routes/app.profiles'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInvestmentsRouteImport } from './routes/app.investments'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as ApiPublicHooksUpdateRatesRouteImport } from './routes/api/public/hooks/update-rates'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/app/transfers',
  path: '/app/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/app/profiles',
  path: '/app/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/app/invoices',
  path: '/app/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/app/investments',
  path: '/app/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/app/insights',
  path: '/app/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/app/categories',
  path: '/app/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/app/bills',
  path: '/app/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/app/accounts',
  path: '/app/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUpdateRatesRoute =
  ApiPublicHooksUpdateRatesRouteImport.update({
    id: '/api/public/hooks/update-rates',
    path: '/api/public/hooks/update-rates',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/update-rates': typeof ApiPublicHooksUpdateRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app': typeof AppIndexRoute
  '/api/public/hooks/update-rates': typeof ApiPublicHooksUpdateRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/update-rates': typeof ApiPublicHooksUpdateRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/investments'
    | '/app/invoices'
    | '/app/profiles'
    | '/app/transactions'
    | '/app/transfers'
    | '/app/'
    | '/api/public/hooks/update-rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/investments'
    | '/app/invoices'
    | '/app/profiles'
    | '/app/transactions'
    | '/app/transfers'
    | '/app'
    | '/api/public/hooks/update-rates'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/investments'
    | '/app/invoices'
    | '/app/profiles'
    | '/app/transactions'
    | '/app/transfers'
    | '/app/'
    | '/api/public/hooks/update-rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppAccountsRoute: typeof AppAccountsRoute
  AppBillsRoute: typeof AppBillsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiPublicHooksUpdateRatesRoute: typeof ApiPublicHooksUpdateRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transfers': {
      id: '/app/transfers'
      path: '/app/transfers'
      fullPath: '/app/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profiles': {
      id: '/app/profiles'
      path: '/app/profiles'
      fullPath: '/app/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/app/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/investments': {
      id: '/app/investments'
      path: '/app/investments'
      fullPath: '/app/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/app/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/app/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/app/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/app/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/update-rates': {
      id: '/api/public/hooks/update-rates'
      path: '/api/public/hooks/update-rates'
      fullPath: '/api/public/hooks/update-rates'
      preLoaderRoute: typeof ApiPublicHooksUpdateRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppAccountsRoute: AppAccountsRoute,
  AppBillsRoute: AppBillsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppIndexRoute: AppIndexRoute,
  ApiPublicHooksUpdateRatesRoute: ApiPublicHooksUpdateRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
