/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppProfilesRouteImport } from './routes/app.profiles'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInvestmentsRouteImport } from './routes/app.investments'
import { Route as AppInstallmentsRouteImport } from './routes/app.installments'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as ApiPublicHooksUpdateRatesRouteImport } from './routes/api/public/hooks/update-rates'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallmentsRoute = AppInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksUpdateRatesRoute =
  ApiPublicHooksUpdateRatesRouteImport.update({
    id: '/api/public/hooks/update-rates',
    path: '/api/public/hooks/update-rates',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/installments': typeof AppInstallmentsRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/update-rates': typeof ApiPublicHooksUpdateRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/installments': typeof AppInstallmentsRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/audit': typeof AppAuditRoute
  '/app': typeof AppIndexRoute
  '/api/public/hooks/update-rates': typeof ApiPublicHooksUpdateRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/installments': typeof AppInstallmentsRoute
  '/app/investments': typeof AppInvestmentsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/update-rates': typeof ApiPublicHooksUpdateRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/insights'
    | '/app/installments'
    | '/app/investments'
    | '/app/invoices'
    | '/app/profiles'
    | '/app/transactions'
    | '/app/audit'
    | '/app/'
    | '/api/public/hooks/update-rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/insights'
    | '/app/installments'
    | '/app/investments'
    | '/app/invoices'
    | '/app/profiles'
    | '/app/transactions'
    | '/app/audit'
    | '/app'
    | '/api/public/hooks/update-rates'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/insights'
    | '/app/installments'
    | '/app/investments'
    | '/app/invoices'
    | '/app/profiles'
    | '/app/transactions'
    | '/app/audit'
    | '/app/'
    | '/api/public/hooks/update-rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksUpdateRatesRoute: typeof ApiPublicHooksUpdateRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profiles': {
      id: '/app/profiles'
      path: '/profiles'
      fullPath: '/app/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investments': {
      id: '/app/investments'
      path: '/investments'
      fullPath: '/app/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/installments': {
      id: '/app/installments'
      path: '/installments'
      fullPath: '/app/installments'
      preLoaderRoute: typeof AppInstallmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/update-rates': {
      id: '/api/public/hooks/update-rates'
      path: '/api/public/hooks/update-rates'
      fullPath: '/api/public/hooks/update-rates'
      preLoaderRoute: typeof ApiPublicHooksUpdateRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBillsRoute: typeof AppBillsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInstallmentsRoute: typeof AppInstallmentsRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBillsRoute: AppBillsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInstallmentsRoute: AppInstallmentsRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppAuditRoute: AppAuditRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksUpdateRatesRoute: ApiPublicHooksUpdateRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}