// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfwialobgdafttpuqwfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmd2lhbG9iZ2RhZnR0cHVxd2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NTczMTIsImV4cCI6MjA5MzIzMzMxMn0.2yENGgoYaRvvjzPquLzWPVWZJLqi-ACBYiTZFBMEw_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});